Lesson 4. Create model. Start write console logic.
Torlopov-Andrey/thinknetica_lessons pull request #1
Opened 2017-08-10 15:34 UTC by Torlopov-Andrey

Main.rb: 
   - Создавать станции
   - Создавать поезда

2017-08-10 21:39 UTC, webmstk requested changes

2017-08-10 21:39 UTC, webmstk commented on lesson_4/lib/model/passenger_train.rb
> +  end
этот метод одинаковый для всех наследников, вынеси его в общий класс

2017-08-10 21:39 UTC, webmstk commented on lesson_4/lib/model/passenger_train.rb
> +    super
проверь, если поезд движется, будет написана ошибка, но вагон при этом добавится?

2017-08-10 21:39 UTC, webmstk commented on lesson_4/lib/model/passenger_train.rb
> +      puts "Need only Carriage!"
Не надо писать сообщения в этих классах. Пусть методы возвращают ложный результат, если что-то не получилось, а ошибки пусть пишет программа, которая дёрнула этот метод.

2017-08-10 21:39 UTC, webmstk commented on lesson_4/lib/model/cargo_train.rb
> +    unless carriage.class == BoxCar
есть ещё методы `is_a?` или 'kind_of?'

2017-08-10 21:39 UTC, webmstk commented on lesson_4/lib/model/train.rb
> +    return @route.stations[@current_station_index + 1] if @current_station_index + 1 < @route.stations.count
Если строка очень длинная, то лучше не использовать постфиксную форму `if`. И можно повторяющееся выражение вынести в переменную
```
next_index = @current_station_index + 1

if next_index < @route.stations.count
  return @route.stations[next_index]
end
```

2017-08-11 04:37 UTC, Torlopov-Andrey commented on lesson_4/lib/model/passenger_train.rb
> +    super
+

2017-08-11 07:31 UTC, vkurennov commented on lesson_4/lib/model/train.rb
> +    return @route.stations[@current_station_index + 1] if @current_station_index + 1 < @route.stations.count
Верно, только это как раз не постфиксная, а префиксная форма if :-)  Постфиксная - это когда if идет после строки кода

2017-08-11 07:36 UTC, vkurennov requested changes

2017-08-11 07:36 UTC, vkurennov commented on lesson_4/lib/controller/train_controller.rb
> +      train = nil
Не обязательно здесь объявлять переменную

2017-08-11 07:36 UTC, vkurennov commented on lesson_4/lib/model/cargo_train.rb
> +  def add_carriage(carriage)
А почему у тебя эти методы в разных классах оличаются? Нужно вынести общие части в базовый класс, а в подклассах сделать только метод сравнения типа вагонов. И его вызывать из базового класса.

2017-08-11 07:36 UTC, vkurennov commented on lesson_4/lib/model/train.rb
> +  def add_carriage(carriage)
Не нужно задавать пустые методы в базовом классе, если они переопределяются. Просто создаешь методы в подклассах и все. Кроме того, не нужно делать их в базовом классе защищенными, а в подклассах - публичными. Подклассы не должны менять видимость методов

2017-08-11 07:42 UTC, webmstk commented on lesson_4/lib/model/train.rb
> +    return @route.stations[@current_station_index + 1] if @current_station_index + 1 < @route.stations.count
ну я комментарий оставил к строке кода с постфиксной формой :)

2017-08-11 07:43 UTC, Torlopov-Andrey commented on lesson_4/lib/model/passenger_train.rb
> +      puts "Need only Carriage!"
+

2017-08-11 08:23 UTC, Torlopov-Andrey commented on lesson_4/lib/model/passenger_train.rb
> +  end
+

2017-08-11 08:28 UTC, Torlopov-Andrey commented on lesson_4/lib/model/train.rb
> +    return @route.stations[@current_station_index + 1] if @current_station_index + 1 < @route.stations.count
+

2017-08-11 08:34 UTC, Torlopov-Andrey commented on lesson_4/lib/controller/train_controller.rb
> +      train = nil
+

2017-08-11 08:41 UTC, Torlopov-Andrey commented on lesson_4/lib/model/cargo_train.rb
> +  def add_carriage(carriage)
+

2017-08-11 08:41 UTC, Torlopov-Andrey commented on lesson_4/lib/model/train.rb
> +  def add_carriage(carriage)
+

2017-08-12 09:49 UTC, vkurennov approved these changes

2017-08-12 09:49 UTC, vkurennov commented on lesson_4/lib/controller/route_controller.rb
> +          puts "Select index of station"
Вот эти части стоило в приватные методы вынести

2017-08-12 09:49 UTC, vkurennov commented on lesson_4/lib/model/train.rb
> +  # Данный метод был приватным, но поскольку он вызывается из публичных методов, то делаем его protected
Так и приватный метод можно вызывать из публичных методов

2017-08-12 09:49 UTC, vkurennov commented on lesson_4/main.rb
> +  def self.add_carrieage_to_train
Разбивай на более мелкие методы. В идеале, метод должен быть не более 10-15 строк

2017-08-12 15:33 UTC, Torlopov-Andrey commented on lesson_4/lib/model/train.rb
> +  # Данный метод был приватным, но поскольку он вызывается из публичных методов, то делаем его protected
Но вроде это нарушает соглашение. Или так нормально делать?

2017-08-12 15:34 UTC, Torlopov-Andrey commented on lesson_4/main.rb
> +  def self.add_carrieage_to_train
ок. Просто тут видимо уже спешил, и хотел побыстрей доделать задачу.

2017-08-12 21:40 UTC, closed without merging