lesson 6. exceptions
Torlopov-Andrey/thinknetica_lessons pull request #4
Opened 2017-08-16 16:50 UTC by Torlopov-Andrey

2017-08-17 08:13 UTC, vkurennov requested changes

2017-08-17 08:13 UTC, vkurennov commented on lesson_6/lib/model/route.rb
> +    @stations = [start, finish]
Тут стоит добавить валидации на то, что переданные аргументы - это именно объекты класса Station

2017-08-17 08:13 UTC, vkurennov commented on lesson_6/lib/model/station.rb
> +    self.register_instance
Зачем тут self?

2017-08-17 08:13 UTC, vkurennov commented on lesson_6/lib/model/station.rb
> +    validate!
Валидировать надо до помещения объекта в массив и регистрации инстанса, иначе у нас будут в массиве не валидные объекты

2017-08-17 08:13 UTC, vkurennov commented on lesson_6/lib/model/train/train.rb
> +    validate!
Опять же - валидировать нужно ДО помещения объекта в хеш

2017-08-17 08:13 UTC, vkurennov commented on lesson_6/lib/model/train/train.rb
> +    @type = nil
Не нужно инициализировать переменные значением nil. При создании объекта, интерпретатор анализирует все инстанс-переменные, которые используются в классе (во всех методах) и все переменные, которые явно не были инициализированы инициализирует значением nil

2017-08-17 08:13 UTC, vkurennov commented on lesson_6/lib/module/validate.rb
> +module Validate
Это сработает только если валидации на атрибуты всегда одинаковые, но если они разные, то будет неудобно.

2017-08-17 19:18 UTC, Torlopov-Andrey commented on lesson_6/lib/model/station.rb
> +    self.register_instance
А когда требуется self? Просто, в других языках, есть понятие свойства класса и понятие ivar (приватная переменная) и например в ios есть рекомендация строгая, все вызывать через self. Так как свойство может быть геттером и дополнительно как-то обрабатываться.

Здесь такого требования нет?

2017-08-17 19:22 UTC, Torlopov-Andrey commented on lesson_6/lib/model/station.rb
> +    validate!
точно! не усмотрел этот момент. Долго бился с подключением модулей и про это забыл.

2017-08-17 19:23 UTC, Torlopov-Andrey commented on lesson_6/lib/model/train/train.rb
> +    @type = nil
+

2017-08-17 19:23 UTC, Torlopov-Andrey commented on lesson_6/lib/model/station.rb
> +    validate!
+

2017-08-17 19:23 UTC, Torlopov-Andrey commented on lesson_6/lib/model/station.rb
> +    self.register_instance
+

2017-08-17 19:24 UTC, Torlopov-Andrey commented on lesson_6/lib/model/train/train.rb
> +    validate!
+

2017-08-18 08:05 UTC, vkurennov commented on lesson_6/lib/model/station.rb
> +    self.register_instance
Нет,  self подразумевается по-умолчанию. Единственное, когда он нужен - это при обращении к сеттеру, иначе интерперетатор решит, что это обращение к локальной переменнной.

2017-08-18 08:09 UTC, vkurennov requested changes

2017-08-18 08:09 UTC, vkurennov commented on lesson_6/lib/model/route.rb
> +  include Validate
Все же неудобно разные методы для разных классов складывать в один модуль. В модуль стоит выносить  общий код, а здесь уже получается вынос специфичных методов, которые не используются в других классах.

2017-08-18 08:09 UTC, vkurennov commented on lesson_6/lib/module/validate.rb
> +    def valid_station?
Вот, пришлось еще и спец метод делать. А должен отрабатывать простой `valid?` Гораздо лучше было бы переопределить метод `validate!` в классе  `Route`, тогда метод `valid?` бы работал как прежде.

2017-08-18 14:44 UTC, Torlopov-Andrey commented on lesson_6/lib/model/route.rb
> +  include Validate
Не могу понять, как сделать так чтоб было удобно :)
Надо разные модули описать для валидации номера, имени и чего-то еще? И подключать отдельно `include Validate::Number` или какая-то иная техника?

2017-08-19 07:32 UTC, iBublik commented on lesson_6/lib/model/route.rb
> +     @stations.each { |station| raise "Array contain not station object!" unless station.instance_of?(Station) }
Я бы так записал:
```ruby
unless @stations.all? { |station| station.is_a?(Station) }
  raise "Array contains not station object!"
end
```
По сути то же самое, но более декларативно. Это просто рекомендация, вдруг что-то новое узнаешь :)

2017-08-19 07:32 UTC, iBublik commented on lesson_6/lib/model/route.rb
> +     true
Методы-команды обычно не возвращают результата. Их задача - выполнить действие, в данном случае пройтись по массиву и бросить исключение, если что-то не так. А метод-запрос `valid?` уже отлавливает исключение и возвращает true/false

2017-08-19 07:32 UTC, iBublik commented on lesson_6/lib/model/station.rb
> +    raise "Name can't be nil" if self.name.nil?
`self` для геттеров не обязательно писать. Он необходим только для сеттеров, чтоб интерпретатор понял, что это не установка локальной переменной

2017-08-19 07:32 UTC, iBublik commented on lesson_6/lib/module/validate_number.rb
> +      raise "Number should be at least 5 symbols" if self.number.to_s.length < 5
А зачем тут приведение к строке? И вообще эта проверка не имеет особого смысла, у тебя регулярка итак длину проверит.

2017-08-19 07:32 UTC, iBublik commented on lesson_6/lib/module/validate_number.rb
> +      raise "Number has invalid formar" if number !~ NUMBER_FORMAT
Где-то ты пишешь с `self`, тут без `self`. Лучше придерживаться единообразия

2017-08-19 07:41 UTC, Torlopov-Andrey commented on lesson_6/lib/model/route.rb
> +     @stations.each { |station| raise "Array contain not station object!" unless station.instance_of?(Station) }
Что значит вдруг? Уже узнал. Пойду с конструкцией потренируюсь.

2017-08-19 07:45 UTC, Torlopov-Andrey commented on lesson_6/lib/model/route.rb
> +     @stations.each { |station| raise "Array contain not station object!" unless station.instance_of?(Station) }
+

2017-08-19 07:46 UTC, Torlopov-Andrey commented on lesson_6/lib/model/route.rb
> +     true
понял!
+

2017-08-19 07:48 UTC, Torlopov-Andrey commented on lesson_6/lib/model/station.rb
> +    raise "Name can't be nil" if self.name.nil?
+

2017-08-19 07:52 UTC, Torlopov-Andrey commented on lesson_6/lib/model/station.rb
> +    raise "Name can't be nil" if self.name.nil?
Короче говоря, self вызываем только у свойств которым присваиваем значения, например
self.name = name
self.number = number

если установка происходит в каком-то методе (сеттере специфичном) мы пишем 
set_name(name) и self в этом случае не нужен. Правильно?

2017-08-19 07:53 UTC, Torlopov-Andrey commented on lesson_6/lib/module/validate_number.rb
> +      raise "Number should be at least 5 symbols" if self.number.to_s.length < 5
я этого не знал %)

2017-08-19 07:55 UTC, Torlopov-Andrey commented on lesson_6/lib/module/validate_number.rb
> +      raise "Number has invalid formar" if number !~ NUMBER_FORMAT
ну вот вроде выше написано в каком случае self нужен. Буду использовать чтобы при обращении к свойству, случайно локальную переменную не создать.

2017-08-19 09:18 UTC, vkurennov approved these changes

2017-08-20 05:59 UTC, merged