lesson 9: metaprogramming
Torlopov-Andrey/thinknetica_lessons pull request #7
Opened 2017-08-22 20:33 UTC by Torlopov-Andrey

2017-08-23 06:38 UTC, iBublik requested changes

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/controller/station_controller.rb
> +      @data <<  station
Лишний пробел)

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/model/station.rb
> +    validate!(:name, :presence)
Список валидаций указывается в самом классе, а не конструкторе. Конструктор должен только вызывать `validate!` без всяких параметров

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/model/station.rb
> +    @@all_instances = [self]
А зачем так делать? У тебя теперь всегда один элемент в массиве будет

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/model/station.rb
> +    validate!(:name, :presence)
Это ко всем классам относится

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/validation.rb
> +    types = [:presence, :format, :type]
Зачем этот массив?

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/validation.rb
> +    case type
Намного удобнее было бы тут через `send` вызывать методы без всяких проверок. Только надо чтоб у всех были одинаковые сигнатуры (неиспользуемые аргументы в Ruby можно схлопнуть с помщью звездочки - `def some_method(arg1, *)`)

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +      raise TypeError, 'method name is not symbol' unless method.is_a?(Symbol)
Зачем нам проверять является ли аргумент символом?

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +      instance_variable_set("@#{method}", nil)
А эта строка зачем? К тому же это создаст переменную на уровне класса.

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +      raise TypeError, 'method name is not symbol' unless method.is_a?(Symbol)
Не вижу смысла в этой проверке. Со строкой тоже можно работать.

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +module Acessors
Не вижу примеров использования модуля. У меня твой код завести не удалось - ни при подключении через extend, ни через include

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +      class_variable_set("@@#{method}_history", nil)
Зачем это в переменной класса хранить? У разных инстансов будет общая история?

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +        history.last
Зачем нам значение из истории брать? Сама переменная-то тоже нужна, геттером можно значение из нее брать

2017-08-23 06:38 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +        class_variable_set("@@#{method}_history".to_sym, history)
В Ruby массивы мутабельны, так что строкой выше ты уже изменил историю (звучит эпично 😄 )

2017-08-23 11:14 UTC, Torlopov-Andrey commented on trainspotting/lib/controller/station_controller.rb
> +      @data <<  station
+

2017-08-23 14:11 UTC, Torlopov-Andrey commented on trainspotting/lib/model/station.rb
> +    @@all_instances = [self]
да, тупанул. %)

2017-08-23 14:12 UTC, Torlopov-Andrey commented on trainspotting/lib/model/station.rb
> +    @@all_instances = [self]
+

2017-08-23 14:14 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +    types = [:presence, :format, :type]
Не нравится через `eval` вызывать, но была задумка (выше хеш) вызывать через eval методы вытаскивая код из хеша. Но че-то не допилил, поэтому стал откатывать к предыдущему решению. 

types был нужен, чтобы проверить что переданный тип находится в указанном массиве. Выгашу его, так как не нужен.

+

2017-08-23 14:45 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      raise TypeError, 'method name is not symbol' unless method.is_a?(Symbol)
ну я думал так, мы пишем 
`attr_accessor_with_history name ...`
и программа руганется на этапе компиляции и сразу будет понятно что надо писать через двоеточие. Хотя исправлю и приведу все к символам. Тогда без разницы будет строка это или символ.

2017-08-23 14:46 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      raise TypeError, 'method name is not symbol' unless method.is_a?(Symbol)
+

2017-08-23 14:48 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +        history.last
+

2017-08-23 14:49 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +        class_variable_set("@@#{method}_history".to_sym, history)
+ %)

2017-08-23 14:49 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      raise TypeError, 'method name is not symbol' unless method.is_a?(Symbol)
+

2017-08-23 14:50 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      instance_variable_set("@#{method}", nil)
Потому что потом когда пишу `get` - если объекта нет - вываливается ошибка, что не корректное имя переменной или метода. Пришлось изначально ее проинициализировать в nil.

2017-08-23 14:51 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      instance_variable_set("@#{method}", nil)
Может где-то в модуле еще ошибка?

2017-08-23 19:16 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +module Acessors
Действительно фигня какая-то. Буду дебажить. Просто, долго бился с модулем. Запустил все и тутже закоммитил.

2017-08-23 19:23 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +module Acessors
Текущий вариант, через extend можно подключить и будет работать. В модуле внизу допишу комментарий с примером использования. Все отрабатывает и выводит как надо.

2017-08-23 19:43 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      class_variable_set("@@#{method}_history", nil)
То есть надо сделать `instance_variable_set` но в методе класса?
Немного смутно понимаю что можно делать с переменными на этих уровнях, а что нельзя.

2017-08-24 05:06 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +module Acessors
Проверял тут - https://repl.it/KUf1/1. Результат:
![image](https://user-images.githubusercontent.com/11278497/29650336-e04abb4e-88b3-11e7-947f-f1d766987393.png)

2017-08-24 05:07 UTC, iBublik commented on trainspotting/lib/module/accessors.rb
> +      raise TypeError, 'method name is not symbol' unless method.is_a?(Symbol)
Ruby не компилируемый язык. Все ошибки возникают только в рантайме.
Но вообще все методы, которые работают с символами, как правило работают и со строками.

2017-08-24 05:09 UTC, iBublik commented
@Torlopov-Andrey кажется ты немного не то делаешь. История должна храниться на уровне инстанса, а не класса. Т.е. мы просто хотим хранить все изменеия переменной у конкретного экземпляра:
```ruby
class A
  attr_accessor_with_history :b
end

a = A.new
a.b = 1
a.b = 2
a.b_history # выведет [1, 2]
```

2017-08-24 05:38 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +module Acessors
Все. Я понял в чем косяк :)
Я, как всегда тупанул и задание не понял. Подумал что надо реализовать этот метод для класса, а не для instance.

2017-08-24 05:38 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      raise TypeError, 'method name is not symbol' unless method.is_a?(Symbol)
+

2017-08-25 12:53 UTC, vkurennov requested changes

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/accessors.rb
> +        instance_variable_set("@#{method}_history".to_sym, []) unless instance_variable_get("@#{method}_history".to_sym)
Кстати, не обязательно to_sym вызывать, будет работать и со строкой

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/accessors.rb
> +        instance_variable_get("@#{method}_history".to_sym).last
Не стоит брать значение из истории, история должна хранить прошлые значения, но должна быть и переменная для атрибута, которая хранит текущее значение.

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/accessors.rb
> +        instance_variable_get("@#{method}_history".to_sym) << v
Здесь надо и саму переменную установить.

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/accessors.rb
> +      instance_variable_set("@#{method}", nil)
Это лишнее, любые переменные автоматом инициализируются nil в момент их первого использования

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +      validations = instance_variable_get(:@validation_hash)[name.to_sym] || []
Зачем тут `instance_variable_get`? Это инстанс-метод модуля `ClassMethods`, у тебя в нем же есть акссессор для `validation_hash`, так и обращайся к аксессору.

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +      instance_variable_get(:@validation_hash)[name.to_sym] = validations
И тут тоже обращайся через акссессор

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +      self.class.instance_variable_get(:@validation_hash).each do |property, validations|
Опять instance_variable_get ни к месту. Зачем тебе тогда  attr_accessor в ClassMethods, если ты его нигде не используешь?

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +        instance_var = instance_variable_get("@#{property}")
А вот здесь как раз к месту применение `instance_variable_get`

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +        validations.each { |hash| send hash.keys.first.to_sym, instance_var, hash.values.first }
А почему опция только одна передается? Там ведь их может быть несколько

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +      raise "Incorrect class! #{value.class}. Need String only." unless value.is_a?(String)
Это тут при чем? На наличие можно проверять атрибуты любых классов.

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +      raise 'Value can\'t be blank' if value.delete(' ').empty?
Наличие атрибута - это если он не nil или не пустая строка/массив

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +      raise 'Not enought params.' unless params.count == 2
задай точный список аргументов метода, тогда не придется проверять их вручную.

2017-08-25 12:53 UTC, vkurennov commented on trainspotting/lib/module/validation.rb
> +    def type(*params)
задай точный список аргументов метода, тогда не придется проверять их вручную.

2017-08-25 12:56 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +        instance_variable_set("@#{method}_history".to_sym, []) unless instance_variable_get("@#{method}_history".to_sym)
+

2017-08-25 12:58 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +        instance_variable_get("@#{method}_history".to_sym).last
+

2017-08-25 12:58 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +        instance_variable_get("@#{method}_history".to_sym) << v
+

2017-08-25 12:59 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      instance_variable_set("@#{method}", nil)
С переменными класса были ошибки, поэтому когда в instance переписывал - не подправил.

2017-08-25 12:59 UTC, Torlopov-Andrey commented on trainspotting/lib/module/accessors.rb
> +      instance_variable_set("@#{method}", nil)
+

2017-08-25 13:03 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +      validations = instance_variable_get(:@validation_hash)[name.to_sym] || []
+

2017-08-25 13:03 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +      instance_variable_get(:@validation_hash)[name.to_sym] = validations
+

2017-08-25 13:07 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +      self.class.instance_variable_get(:@validation_hash).each do |property, validations|
+

2017-08-25 13:07 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +        instance_var = instance_variable_get("@#{property}")
+

2017-08-25 14:37 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +        validations.each { |hash| send hash.keys.first.to_sym, instance_var, hash.values.first }
+

2017-08-25 14:44 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +      raise "Incorrect class! #{value.class}. Need String only." unless value.is_a?(String)
Ну, вроде бы исправил. Объекты проверяем на nil, а если это строка, то дополнительно проверяем чтоб пробелов не было.

2017-08-25 14:46 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +      raise 'Value can\'t be blank' if value.delete(' ').empty?
+

2017-08-25 14:58 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +      raise 'Not enought params.' unless params.count == 2
Заглупил немного. Раньше функциями на подобии `send` не ползовался. %)

2017-08-25 14:58 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +      raise 'Not enought params.' unless params.count == 2
+

2017-08-25 14:58 UTC, Torlopov-Andrey commented on trainspotting/lib/module/validation.rb
> +    def type(*params)
+

2017-08-25 16:16 UTC, vkurennov approved these changes

2017-08-25 16:31 UTC, merged